version: "0.1"
services:
  shell-ui:
    image: shell-ui
    ports:
      - "4200:8080"
  db:
    image: postgres
    environment:
      - "POSTGRES_PASSWORD=root"
      - "POSTGRES_USER=root"
      - "POSTGRES_DB=monitoring"
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    command: "server /data --console-address \":9001\""

  monitoring-manager:
    image: monitoring-manager:dev
    depends_on:
      - db
      - minio
    environment:
      - "AWS_REGION=us-west-1"
    ports:
      - "8080:8080"
      - "8081:8081"

  be:
    image: profiler:latest
    depends_on:
      - monitoring-manager
    ports:
      - "5000:5000"
    environment:
      - "AWS_ACCESS_KEY_ID=minioadmin"
      - "AWS_SECRET_ACCESS_KEY=minioadmin"
