version: "0.1"
services:
  fe:
    build:
      context: ../profiler-fe
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  be:
    image: hydrosphere/profiler:latest
    ports:
      - "5000:5000"
    environment:
      - "PROFILER_INDEPENDENT_MODE=True"

