name: Backend CI

on:
  pull_request:
    paths:
      - "profiler/**"

jobs:
  Test:
    runs-on: ubuntu-20.04
    name: "Setup Python & Run Tests"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8

      - name: Setup poetry
        uses: abatilo/actions-poetry@v2.1.0
        
      - name: Install dependencies
        shell: bash
        run: "cd profiler && poetry install"

      - name: Test code
        shell: bash
        run: "cd profiler && poetry run pytest tests"
